Adding the google one-tap authentication
wohaoshuai/note-taker-backend pull request #4
Opened 2022-05-03 05:39 UTC by bluzeey

The following PR adds in a mongodb connection to which the data about the user could be send through decoding the google-oauth-token generated in the frontend. A rough implementation, it requires the env variables to be protected and a helper function down the road for cross checking whether the user exists in the database.

2022-05-03 05:41 UTC, bluzeey commented
Also google o-auth should added in the requirements.txt , if required down the line.

2022-05-04 02:13 UTC, yumochi commented on app.py
> +cluster=MongoClient("mongodb+srv://SahilMaheshwari:sahil123@cluster1.ir5lh.mongodb.net/myFirstDatabase?retryWrites=true&w=majority",tls=True,
we  need to move the url into env variable

2022-05-04 02:13 UTC, yumochi commented on app.py
> +db=cluster["assembo"]
I would move the name into env variable

2022-05-04 02:14 UTC, yumochi requested changes
Refer to my comments

2022-05-07 02:14 UTC, yumochi commented on app.py
> +    print(decoded_token)
please remove testing code here

2022-05-13 02:38 UTC, yumochi approved these changes

2022-05-13 02:38 UTC, merged